# Travis CI settings

language: python

python:
  - 2.7.12
  - 3.5.2

before_install:
  - touch utils/envs.py
  - echo "ACCESS_KEY=''" > utils/envs.py

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt

script:
  - invoke test
  - invoke syntax
