# Travis CI settings

language: python

python:
  - 2.7
  - 3.4

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then export SUBPATH=python2; else export SUBPATH=python3; fi

script:
  - python -m pytest --doctest-modules $SUBPATH/ tests/$SUBPATH/    # Unit tests
  - python -m pylint $SUBPATH/ tests/$SUBPATH/                      # Syntax validation
