# Travis CI settings

language: python

python:
  - '2.7'

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python -m pytest --doctest-modules  # Unit tests
  - python -m pylint src/ tests/        # Syntax validation
